server:
  port: '9000'
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpia
    username: nnpia
    password: nnpia
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
